### ISSUE TITLE
Sensors update only every ~30 minutes

### ISSUE THREAD

**Issue by kamwill** [tijsverkoyen/Home-Assistant-FusionSolar-Kiosk#20]
All of the sensors are update around every 30 minutes. The issue started occurring, when the new version of Fusion Solar was introduced. I've seen in the code that the update is set for 300 secs, but it seems not to work this way.

**Comment by fcqpl** [comment]
Looks like FusionSolar kiosk site now it's updating every 30 minutes.

**Comment by tijsverkoyen** [comment]
Every 300 seconds a call is done to Fusion Solar, the integration uses the data that is retrieved by that call.

I have just tested this locally and set the interval to 10seconds, and the realTimePower seems to update more frequently than 30minutes on my integration.

To be honest, there is not much I can do here. I would suggest to check if the same behaviour is present in the kiosk itself, and if so you should contact Fusion Solar support directly.
