### ISSUE TITLE
Energy Panel doesn't show realtime entity

### ISSUE THREAD

**Issue by Brusta37** [tijsverkoyen/Home-Assistant-FusionSolar-Kiosk#21]
Energy Panel doesn't show realtime entity, only the historical data (daily, monthly, yearly, lifetime production).
I'm not able to add the realtime data to the Solar Panel configuration

**Comment by eternum79** [comment]
It's the same for me. I have the sensor.solar huawe_ real_time_power, but I can't add it to the energy board. Why?

**Comment by decisoft** [comment]
Same here. Any update/solution? Thanks

**Comment by tijsverkoyen** [comment]
I can't reproduce this problem. Do you get an error when you try to add the sensor to the dashboard?
Or are you trying to add the Realtime Power entity to the Energy Dashboard? If so: try adding the Total Lifetime Energy entity.
