### ISSUE TITLE
Invalid Add-on repository! when trying to install it

### ISSUE THREAD

**Issue by Pauga99** [tijsverkoyen/Home-Assistant-FusionSolar-Kiosk#22]
Hi, im trying to install this repository on my home assistant but when i try to add the repository this message continues to pop up:
![image](https://user-images.githubusercontent.com/36281051/160234127-96129d1c-c1d9-4cb1-91fa-e1e53f16c613.png)

The link i'm using is: https://github.com/tijsverkoyen/Home-Assisant-FusionSolar-Kiosk , i think i'm doing it right but it doesn't work, ive tried it with the HA installation i use in my house and i've tried it in a fresh install and it doesn't work on neither of them.

Thanks for the help!

**Comment by Roberthblomberg** [comment]
You need to install HACS and inside that install the link you have. 
HACS / integrations / push the three dots up right -> Custom repositories

**Comment by tijsverkoyen** [comment]
See https://hacs.xyz/docs/faq/custom_repositories also
