### ISSUE TITLE
No funciona

### ISSUE THREAD

**Issue by saboret73** [tijsverkoyen/Home-Assistant-FusionSolar-Kiosk#23]
Hola, sigo todos los pasos pero cuando voy a integraciones no me sale la integración, pero si que la tengo instalada y configurada.

**Comment by tijsverkoyen** [comment]
Yeah, not that much information. Do you get an error? Are you not seeing any entities created? 
The integration has no dashboards, widgets, ... it creates some entities that should be added to your dashboards manually.
