### ISSUE TITLE
error from start of mei

### ISSUE THREAD

**Issue by carbone15** [tijsverkoyen/Home-Assistant-FusionSolar-Kiosk#24]
Hello,
I was using fusionsolar plugin for HA, without any problem, but after 2nd of mei I don't receive data anymore, and have error message in log:
 
> File "/config/custom_components/fusion_solar_kiosk/__init__.py", line 111, in state
>     return float(self.coordinator.data[self._kioskId][ATTR_DATA_REALKPI][self._attribute]) if self.coordinator.data[self._kioskId][ATTR_DATA_REALKPI] else None
> KeyError: 'realTimePower'
> 2022-05-09 14:05:22 ERROR (SyncWorker_8) [custom_components.fusion_solar_kiosk.fusion_solar_kiosk_api] Retrieving the data failed with failCode: 0, data: neteco.pvms.systemSetting.notExists
> 2022-05-09 14:05:22 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 137, in _handle_refresh_interval
>     await self._async_refresh(log_failures=True, scheduled=True)
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 270, in _async_refresh
>     update_callback()
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 330, in _handle_coordinator_update
>     self.async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
>     self._async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
>     state = self._stringify_state(available)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
>     if (state := self.state) is None:
>   File "/config/custom_components/fusion_solar_kiosk/__init__.py", line 111, in state
>     return float(self.coordinator.data[self._kioskId][ATTR_DATA_REALKPI][self._attribute]) if self.coordinator.data[self._kioskId][ATTR_DATA_REALKPI] else None
> KeyError: 'realTimePower'
> 2022-05-09 14:10:22 ERROR (SyncWorker_10) [custom_components.fusion_solar_kiosk.fusion_solar_kiosk_api] Retrieving the data failed with failCode: 0, data: neteco.pvms.systemSetting.notExists
> 2022-05-09 14:10:22 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 137, in _handle_refresh_interval
>     await self._async_refresh(log_failures=True, scheduled=True)
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 270, in _async_refresh
>     update_callback()
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 330, in _handle_coordinator_update
>     self.async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
>     self._async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
>     state = self._stringify_state(available)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
>     if (state := self.state) is None:
>   File "/config/custom_components/fusion_solar_kiosk/__init__.py", line 111, in state
>     return float(self.coordinator.data[self._kioskId][ATTR_DATA_REALKPI][self._attribute]) if self.coordinator.data[self._kioskId][ATTR_DATA_REALKPI] else None
> KeyError: 'realTimePower'
Does anyone have an idea of the root cause?

**Comment by carbone15** [comment]
Hello,
I didn't receive an answer but I found the reason.
I think that fusion solar change is data's, and now this addon is not able to understand it anymore. And I found an other URL that will send the correct dataset.
Wrong url: "https://region01eu5.fusionsolar.huawei.com/pvmswebsite/nologin/assets/build/index.html#/kiosk?kk=DEs70t23cC"
Correct URL: "https://region01eu5.fusionsolar.huawei.com/rest/pvms/web/kiosk/v1/station-kiosk-file?kk=DEs70t23cC"
You just need to adapt the kiosk code with your code after "kk="  (don't worry, it's not my real code :) )

**Comment by tijsverkoyen** [comment]
Can you check if you have the latest version (3.0.0) installed? If not: make sure you update your configuration: https://github.com/tijsverkoyen/Home-Assistant-FusionSolar-Kiosk/releases/tag/v3.0.0

Huawei has started to use several urls for the kiosk, and also the data structure (as you mentioned) has been changed, but all this was fixed in v3.0.0.
