### ISSUE TITLE
Add more sensors

### ISSUE THREAD

**Issue by alexmc1510** [tijsverkoyen/Home-Assistant-FusionSolar-Kiosk#25]
Hello,

Thanks for the addon. It works like a charm. I can see that the only sensors available are:
ID_REALTIME_POWER
ID_TOTAL_CURRENT_DAY_ENERGY
ID_TOTAL_CURRENT_MONTH_ENERGY
ID_TOTAL_CURRENT_YEAR_ENERGY
ID_TOTAL_LIFETIME_ENERGY

Is there any plan to include more sensors related power consumption at home? Could I help you to integrate them? If you give me some hints about your development I can try to integrate the rest.

Thanks in advance.

**Comment by carbone15** [comment]
Hello,
so it means that it still work for you? because for me they change the kiosk result, it s not a json anymore and I don't have result, so I can't use other sensor, ...

**Comment by tijsverkoyen** [comment]
At this point the endpoint the integration is using only returns this data:
```
{
  'realTimePower': '1.23', 
  'cumulativeEnergy': 1234.56, 
  'monthEnergy': 123.45, 
  'dailyEnergy': 1.23, 
  'yearEnergy': 12345.67
}
```

I don't see how engere consumption at home can be included from this. Or do you have an energy storage (battery) solution, and do you have more data?
