### ISSUE TITLE
Connect with API

### ISSUE THREAD

**Issue by dagna1001** [tijsverkoyen/Home-Assistant-FusionSolar-Kiosk#26]
Hello!

Im the owner, but not the installer... The installer has shared me an user/password for the openAPI rather than the kiosk

He shared also me the plant in fusionsolar but i dont have the kiosk option (because only the installer has it...)

is there any mode to connect your integration with user/password rather than with the URL?

**Comment by tijsverkoyen** [comment]
Are you able to login in with that credentials on https://eu5.fusionsolar.huawei.com/unisso/login.action?service=%2Funisess%2Fv1%2Fauth%3Fservice%3D%252Fnetecowebext%252Fhome%252Findex.html? If so you should have a button "Kiosk" at the top right corner of the screen.

If not you should contact your installer to give you access to the portal.
