### ISSUE TITLE
Energy page - Solar production - Correcting data with Solar information from yesterday

### ISSUE THREAD

**Issue by NickBootOne** [tijsverkoyen/Home-Assistant-FusionSolar-Kiosk#28]
When viewing the energy page I see some kind of correction at the beginning of the day at 0:00 - 1:00 and  1:00 - 2:00.
Looks like the same amount of total Solar energy from the day before but why is it in the next day with an direct correction.

So in the morning I have for example an -30kWh and the next hour I have +30kWh of Solar energy.

If there are any questions please let me know

Thanks !

**Comment by varn-lt** [comment]
![image](https://user-images.githubusercontent.com/45877788/177514580-67972928-2b9f-498b-b0bd-0706dddea417.png)

**Comment by NickBootOne** [comment]
![Greenshot 2022-07-06 11 12 38](https://user-images.githubusercontent.com/59101602/177515280-f8a138db-9edc-43a0-87ac-f39d43165e62.png)

**Comment by Seweryn101** [comment]
Hi!
Anyone have a fix for the problem?

**Comment by NickBootOne** [comment]
> > Hi! Anyone have a fix for the problem?
> 
> I have modified the energy dashboard and switched from total energy meter to daily (from this integration), where the daily energy meter does not have such +- of energy gaps.

That is not a solution or a workaround because if you do that the info for used solar energy is no longer displayed.

**Comment by varn-lt** [comment]
> > > Hi! Anyone have a fix for the problem?
> 
> > 
> 
> > I have modified the energy dashboard and switched from total energy meter to daily (from this integration), where the daily energy meter does not have such +- of energy gaps.
> 
> 
> 
> That is not a solution or a workaround because if you do that the info for used solar energy is no longer displayed.

It works for me 
![image](https://user-images.githubusercontent.com/45877788/178346047-9879fc97-607f-44ee-9444-cc3f8a4ca731.png)

**Comment by tijsverkoyen** [comment]
I don't see that drops in my integration, but could you tell me how your energy dashboard is configured? Or where do you see these graphs with the drops?

**Comment by NickBootOne** [comment]
![image](https://user-images.githubusercontent.com/59101602/182357864-6cda1cea-0286-4855-bbf5-9fe406fe4a36.png)

**Comment by tijsverkoyen** [comment]
Thx. I will try to see if I can reproduce the issue. But probably this is something related to the data the integration receives from Huawei Fusion Solar.

**Comment by AndersHoglund** [comment]
I have the same issue. 
Could it be a fix/workaround to have a validation on incoming lifetime energy where negative drops from prev. value are rejected.

**Comment by AndersHoglund** [comment]
Another thought. Could it be a Date and Time zone problem? Client being 1 or more hours ahead of the server. Could cause problems at midnight. I.e. client asks for today's data at 00:00, server is still on yesterday and responds with data for yesterday 00:00. I am in CET (Stockholm) with DST (GMT +2), a user in the GMT zone might not see the problem.

**Comment by AndersHoglund** [comment]
Tried changing from GMT+1 to GMT, no difference. Looking at sensor history, it is clear that data for 00:00 - 01:00 is one day old. Will try GMT without DST next.
![problem](https://user-images.githubusercontent.com/15121917/183269037-82941877-0b69-4308-b373-89aaf70a20e7.png)
.

**Comment by AndersHoglund** [comment]
This is a Huawei problem! 
I ran the Fusionsolar kiosk url in firefox, no HA components involved. Attached cut outs from screenshots speaks for them selfs.
Only thing that can be done in HA is checking and rejecting invalid data.
/A
![SolarFusionKioskResponse](https://user-images.githubusercontent.com/15121917/183314693-b1da02a9-2d4e-43d9-abc8-ca458efb0a00.png)

**Comment by tijsverkoyen** [comment]
First of all: I'm very sorry this took this long.

I have a fix ready (https://github.com/tijsverkoyen/Home-Assistant-FusionSolar-Kiosk/pull/33) and will test this tonight, of this works I will publish a new release this week.

Thx @AndersHoglund for the PR you did, which made me see the 💡. I was totally working on a wrong approach.

**Comment by tijsverkoyen** [comment]
This issue is fixed in the v3.0.1 release.
