### ISSUE TITLE
realTimePower not listed to be add in HA Energy section. What sensor to choose?

### ISSUE THREAD

**Issue by hirofairlane** [tijsverkoyen/Home-Assistant-FusionSolar-Kiosk#30]
Hello thanks a lot for the integration, I think it is the best approach for the people that don't want to get their hands dirty messing around with the inverter hardware.

The problem is that I'm trying to setup the power consumption in the HA Energy card, but I'm not sure what sensor to choose. The "realtime" sensor is not listed, and the "accumulated" returns generation over the night.

What option should I choose?

**Comment by AndersHoglund** [comment]
Select entity "Total lifetime energy".
/A

**Comment by hirofairlane** [comment]
Thanks a lot
