### ISSUE TITLE
Implementation Request

### ISSUE THREAD

**Issue by jesusma32** [tijsverkoyen/Home-Assistant-FusionSolar-Kiosk#35]
Hi thanks for your work.

Is it possible to show house power consumption, and the power goes to red?

Thanks

**Comment by tijsverkoyen** [comment]
Could you clarify what you want exactly? Because I don't understand it.

**Comment by tijsverkoyen** [comment]
Yeah, still don't get it. Could you for example give me a screenshot and mark which info you want to be available in Home Assistant? 

I only have solar panels, no battery so probably I probably don't have the same data in my kiosk as you. If you want you can send me an email (fusionsolar at verkoyen.eu) with your kiosk url.

**Comment by jesusma32** [comment]
Grid, PV And Load. With this 3 inputs just perfect. Thanks [image0.png]

Enviado desde mi iPhone

El 5 oct 2022, a las 8:46, Tijs Verkoyen ***@***.***> escribió:

﻿

Yeah, still don't get it. Could you for example give me a screenshot and mark which info you want to be available in Home Assistant?

I only have solar panels, no battery so probably I probably don't have the same data in my kiosk as you. If you want you can send me an email (fusionsolar at verkoyen.eu) with your kiosk url.

**Comment by tijsverkoyen** [comment]
![Cursor_and_https___region04eu5_fusionsolar_huawei_com_pvmswebsite_nologin_assets_build_index_html__kiosk_kk_M2v00roaxA](https://user-images.githubusercontent.com/250042/194005095-1a5efff6-be77-4cf1-acb8-61028f41e6b3.png)

This is the information that is available in my Kiosk. Realtime power, yield today, yield this month, yield this year and total yield are send to Home Assistant.

I don't see grid, pv or load.

**Comment by jesusma32** [comment]
Sorry, i have the same as you. Screen capture is from web page fusión solar.
Thanks for your work 👍🏻👏🏻👏🏻

Enviado desde mi iPhone

El 5 oct 2022, a las 9:34, Tijs Verkoyen ***@***.***> escribió:

﻿

[Cursor_and_https___region04eu5_fusionsolar_huawei_com_pvmswebsite_nologin_assets_build_index_html__kiosk_kk_M2v00roaxA]<https://user-images.githubusercontent.com/250042/194005095-1a5efff6-be77-4cf1-acb8-61028f41e6b3.png>

This is the information that is available in my Kiosk. Realtime power, yield today, yield this month, yield this year and total yield are send to Home Assistant.

I don't see grid, pv or load.
