### ISSUE TITLE
Kiosk service unavailable make issue with HA Recorder

### ISSUE THREAD

**Issue by olibos** [tijsverkoyen/Home-Assistant-FusionSolar-Kiosk#37]
Hello,

On the first of octobre, I've received an error telling me that it cannot parse a float from 'unavailable'.
Even if the sensors updates after the crash, HA recorder does not update the long term statistics and then the Energy dashboard does not show any power production after the first crash.

I've restarted HA and the system catch up and the statistics are updated.

But... This night, I had the same error with the same outcome, here is my log details:
```
2022-10-03 00:25:48.135 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 151, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 348, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/fusion_solar_kiosk/__init__.py", line 69, in state
    if float(new_value) < float(current_value):
ValueError: could not convert string to float: 'unavailable'
```

As you can see: 
![image](https://user-images.githubusercontent.com/6031263/193570213-3da67ddf-6b65-4959-b3fe-3a7fa6d1b49a.png)
There is no production recorded between 8 to 10 and at 11 the system is rebooted and catch up.

I'll try to update the condition on a fork and let you know if the problem disapears.

**Comment by olibos** [comment]
Here is my workaround:
https://github.com/olibos/Home-Assistant-FusionSolar-Kiosk/blob/fix/handle-unavailable-ws/custom_components/fusion_solar_kiosk/__init__.py#L75-L77

I'll check if it works for me in the coming days.
If everything is OK I'll make a PR 😉

**Comment by AndersHoglund** [comment]
I have seen the same problem twice. Root cause for "unavailable" seems to be too many kiosk requests. 
I have copied @olibos  workaround, looks like a proper fix to me. Thank you. we will see if it works....

**Comment by AndersHoglund** [comment]
It happened again last night, to many requests.  And sorry to say the fix suggested above did not help. I do not really understand why...

``` File "/config/custom_components/fusion_solar_kiosk/__init__.py", line 79, in state
    if float(new_value) < float(current_value):
ValueError: could not convert string to float: 'unavailable'
```

Question is if "`new_value`" or "`current_value`" is "unavailable"? Only "`new_value`" is validated by the fix.....

**Comment by olibos** [comment]
Hello,

Thank you for your feedback.

Just to be sure, have you restart HA after applying the workaround?
Can you post the crash log (with stacktrace)?

I have no more issue since 3rd of Octobre, but I have no warning as well 😉...

In the meantime, I've posted a new version with logging on both values 😉!
https://github.com/olibos/Home-Assistant-FusionSolar-Kiosk/blob/fix/handle-unavailable-ws/custom_components/fusion_solar_kiosk/__init__.py#L75-L81

Have a nice day

**Comment by AndersHoglund** [comment]
Yes, did restart HA. Please find the complete logfile attached. 
Funny, no trace of your warning log. I will re-upload your _init_.py, maybe I did something wrong when only editing in place and adding the few lines in this file. It looks OK, but I am a python rookie, tabs or spaces may fool you.
/A

[home-assistant.log.zip](https://github.com/tijsverkoyen/Home-Assistant-FusionSolar-Kiosk/files/9716494/home-assistant.log.zip)

**Comment by olibos** [comment]
Hello @AndersHoglund ,

You were right!
![image](https://user-images.githubusercontent.com/6031263/194236951-7d413368-d3f7-428c-b86e-dfbf57d55117.png)
It's the current value which was unavailable...

And this time I see another error few minutes before:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/fusion_solar_kiosk/sensor.py", line 43, in async_update_data
    ATTR_DATA_REALKPI: await hass.async_add_executor_job(api.getRealTimeKpi, kiosk.id)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/fusion_solar_kiosk/fusion_solar_kiosk_api.py", line 32, in getRealTimeKpi
    if not jsonData[ATTR_SUCCESS]:
KeyError: 'success'
```
It's maybe linked to quota  you mentionned.

I'll add more logging to diagnose.

Note: sending "0" is not the best idea because it mess with statistics, @tijsverkoyen do you knwo what i can send to avoid that?

**Comment by tijsverkoyen** [comment]
@olibos maybe we should not return anything at all, but just raise an error, something like (untested):
````python
if entity is not None:
  current_value = entity.state
  if not isfloat(current_value):
    raise HomeAssistantError(f'Current value is not valid: {current_value}')

  new_value = self.coordinator.data[self._kioskId][ATTR_DATA_REALKPI][self._attribute]
  if not isfloat(new_value):
     _LOGGER.warning(f'{self.entity_id}: new value ({new_value}) is not a float, so not updating.')
    return float(current_value)

  if float(new_value) < float(current_value):
    _LOGGER.debug(f'{self.entity_id}: new value ({new_value}) is smaller then current value ({entity.state}), so not updating.')
    return float(current_value)
````

**Comment by olibos** [comment]
Thanks @tijsverkoyen ,

I've also found: 
```python
from homeassistant.helpers.update_coordinator import (
    CoordinatorEntity,
    DataUpdateCoordinator,
    UpdateFailed,
)

raise UpdateFailed(f"Error communicating with API: {err}")
```
from https://developers.home-assistant.io/docs/integration_fetching_data/

For now, I've just catch the `KeyError` in `custom_components\fusion_solar_kiosk\fusion_solar_kiosk_api.py` and add some logs to see if it's not the root cause.

I'll keep you posted

**Comment by AndersHoglund** [comment]
OK, just noticed the odd behavior too, no warnings in my logs.
Theory, the validation code does not catch the first instance of crap data. The condition in the last return statement might be incomplete/incorrect storing crap data in the database.

`    return float(self.coordinator.data[self._kioskId][ATTR_DATA_REALKPI][self._attribute]) if self.coordinator.data[self._kioskId][ATTR_DATA_REALKPI] else None`

I think we would be better of handling this in the api layer, as I did in my first suggestion. Not letting crap data go this far into the system, stopping it at the gate.
/A 
![LifeTimeEnergyGlitch](https://user-images.githubusercontent.com/15121917/194262637-157d5864-0645-4a37-bd23-8ae846c87c96.png)

**Comment by AndersHoglund** [comment]
Yeah, and I handled that in the api. With an ugly global.... Must be a better way, but if not; fine. Logic in this layer is becoming too complex now. But it might be possible to cleanup by refactoring.
/A

**Comment by olibos** [comment]
Hello @AndersHoglund, @tijsverkoyen,

Tonight I had the same problem... **But**, without any issue in recorder nor statistics catch up!
Here are my logs:
![image](https://user-images.githubusercontent.com/6031263/194520967-6d2466d9-8711-413a-8d78-0be4f6516c80.png)
the 'success' error is the message of the added [KeyError catch](https://github.com/olibos/Home-Assistant-FusionSolar-Kiosk/blob/master/custom_components/fusion_solar_kiosk/fusion_solar_kiosk_api.py#L41:L43)

```json
{"exceptionType":"ROA_EXFRAME_EXCEPTION","exceptionId":"framwork.remote.SystemError"}
```

Is the API exception which seems not related to a request quota but just some issue on their end.

With the catch in `getRealTimeKpi` I've no more `unavailable` in current_value, which seems to fix my problem.

**Comment by AndersHoglund** [comment]
Great. Catching errors already at the http link layer is the best way. But error message "success" seems odd to me. 
Is it this initial type of error that is caught? (from my prev. log):
`2022-10-05 04:47:42.016 ERROR (MainThread) [custom_components.fusion_solar_kiosk.sensor] Error requesting FusionSolarKiosk data: HTTPSConnectionPool(host='region02eu5.fusionsolar.huawei.com', port=443): Max retries exceeded with url: /rest/pvms/web/kiosk/v1/station-kiosk-file?kk=q9KgDdcj4L (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f77c4f310>: Failed to establish a new connection: [Errno -3] Try again'))`
Or are there more kinds of kiosk API errors besides "Max retries"? I have a hard time seeing how the error in my log above could be a "key error". Maybe` Errno -3` means KeyError? 
/A
